#!/bin/bash
# SPDX-FileCopyrightText: Copyright (c) <year> NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Assume we are in project directory
source ./80scripts/service.sh # Source the service scripts
# ---------------------------------------------------------------------
function __run_cmd() {	cmd=("$@"); echo -e "\e[1;33m************************ ${cmd}\e[0;39m"; eval ${cmd}; }
function __run_cmd_fs() {	cmd=("$@"); ${IOCTL_EXE_PATH} ${MDS_IP} M Logs_write \"${cmd}\"; __run_cmd "${cmd}"; }

function UNITEST_compile_success() {
	./z_gusli_clnt_unitest -h;
	LD_LIBRARY_PATH=./99bin/inst/lib ./z_gusli_clnt_unitest_dyn -h;
}

function UNITEST_SPDK_both() {
	echo_green ".....Test ctrl+c";
	rm out_*;
	sudo ./z_gusli_spdk_both_unitest @s 2>&1 | tee -a out_srvr.txt &
	     ./z_gusli_spdk_both_unitest @c 2>&1 | tee -a out_clnt.txt
	wait;
	GUSLI show;
}

# ---------------------------------------------------------------------
# See how we were called.
case "$1" in
  spdk_both) UNITEST_SPDK_both;;
  all|All)
	UNITEST_compile_success
	UNITEST_SPDK_both;
	echo_green "************************ All tests Done";
	;;
  *)
	echo $"Usage: $0 {1 of the options below}";
	echo_yellow "  ------------ Unitests of sub components:";
	echo "    spdk_both         - SPDK backend server with client, simple io";
	echo "    all               - Full CI test suit";
	exit 2
esac
RETVAL=$?
echo
exit $RETVAL
